---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10833.
--- DateTime: 2022/10/31 20:53
----- redis.call redis的命令  keys 用来存key的  argv 用来存其他的参数的
---
--接收用户的id
local userId = ARGV[1];
--接收秒杀券的id
local seckill = ARGV[2];
---接收的orderid
local orderId = ARGV[3]
--库存key
local stockKey = 'seckill:stock:' .. seckill;
--订单key
local orderKey = 'seckill:order:' .. seckill;

--判断库存是否从充足
if(tonumber(redis.call('get',stockKey)) <=0)then
    return 1;
end
--判断用户是否下档
if (redis.call('sismember',orderKey ,userId) == 1) then
    return 2;
end
--可以下单
--扣减库存
redis.call('incrby',stockKey,-1)
--将用户存入优惠券集合
redis.call('sadd',orderKey,userId);
--添加一个消息队列组   第一个是创建stream组的指令  第二个设置组的名字  * 表示消息的名字由redis自己创建  后秒的表示消息的记录
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',seckill,'id',orderId);
return 0;



